[package]
name = "isometric"
version = "0.1.0"
authors = ["Thomas Elder <tgelder@gmail.com>"]

[dependencies]
nalgebra = "0.17.2"
gl = "0.11.0"
glutin = "0.19.0"
image = "0.21.0"
glium = "0.23.0"
conrod_core = "0.63.0"
conrod_glium = "0.63.0"
conrod_winit = "0.63.0"